### ISSUE TITLE
tensorboard and tensorflow app in windows with tensorflowsharp

### ISSUE THREAD

**Issue by halukmy** [tengge1/learn-tensorflow#1]
will you update?

thanks

**Comment by tengge1** [comment]
@halukmy Why would you like tensorflowsharp more than tensorflow with python?

**Comment by halukmy** [comment]
C# is love and powerful like iron man :) swift is captain america python like hulk lol

.net is powerfull and now opensource and platform freee also based on C++

**Comment by halukmy** [comment]
also check my tshirt lol :D
